### ISSUE TITLE
height: 100% not working

### ISSUE THREAD

**Issue by ghost** [yansern/vue-multipane#10]
Thanks for a great component!

I ran into the following issue: I'd like the panes to take up 100% of the available space. 

In the demo code (1st example), I tried setting height to 100% instead of 400px.
This seems to disable the slider control and fixes the window height to the content size, rather than available space.

How can I size the panes to occupy the entire available space vertically?

**Comment by yurayko** [comment]
```
<style>
.multipane {
  height: 100vh;
}
</style>
```
or other parent block

**Comment by ghost** [comment]
Thanks, sorry for not closing sooner
